apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

commonLabels:
  env: dev
  cluster: dev-demo

namePrefix: dev-

patches:
- path: deployment-dev.yaml
- path: service-dev.yaml

images:
 - name: nginx
   newTag: dev
