apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 5
template:
  spec:
    containers:
    - name: nginx
      resources:
        limits:
          cpu: "200"
          memory: "1Gi"
        requests:
          cpu: "100"
          memory: "500Mi"