apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

labels:
  - pairs:
      env: prod
      release: Q2

namePrefix: prod-

patches:
- path: deployment-prod.yaml
- path: service-prod.yaml

images:
 - name: nginx
   newTag: prod
